version: 2
updates:
  - package-ecosystem: "npm"
    directory: "client/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "sunday"
      time: "10:00"
    open-pull-requests-limit: 20
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Europe/Berlin"
      day: "sunday"
      time: "10:00"
