name: Test Client

on:
  push:
    paths:
      - "client/**"
    branches:
      - main
  pull_request:
    paths:
      - "client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Check-out
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint source files
        run: npm run lint

      - name: Build project
        run: npm run build
